# Series 클래스

In [1]:
import pandas as pd

In [2]:
s = pd.Series([1,3,5,7,9])
print(s)

0    1
1    3
2    5
3    7
4    9
dtype: int64


In [3]:
print(s.index)

RangeIndex(start=0, stop=5, step=1)


In [4]:
print(s.values)

[1 3 5 7 9]


In [5]:
s = pd.Series([9904312, 3448737, 2890451, 2466052],
              index=["서울","부산","인천","대구"])
print(s)

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64


In [6]:
print(s.index)

Index(['서울', '부산', '인천', '대구'], dtype='str')


In [7]:
print(s.values)

[9904312 3448737 2890451 2466052]


In [8]:
s.name = "인구"
s.index.name = "도시"
print(s)

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64


In [9]:
s.index.name = None
print(s)

서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64


In [10]:
print(pd.Series(range(1,5)))

0    1
1    2
2    3
3    4
dtype: int64


In [11]:
s= pd.Series(['samsung',8100])
print(s)

0    samsung
1       8100
dtype: object


타입이 섞여있으면 object타입으로 됨
계산하려면 형변환필요

In [12]:
from pandas import Series

data = [1000,2000,3000]
s = Series(data)        
print(s.index)
print(s.index.to_list())

RangeIndex(start=0, stop=3, step=1)
[0, 1, 2]


In [13]:
data = [1000, 2000, 3000]
s = Series(data)
s.index = ['메로나', '구구콘', '하겐다즈']
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [14]:
data = [1000, 2000, 3000]
index = ['메로나', '구구콘', '하겐다즈']
s = Series(data = data, index=index)          # s = Series(data,index)    # s = Series(index=index, data=data)
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [15]:
s2 = s.reindex(['메로나','비비빅','구구콘'])
print(s2)

메로나    1000.0
비비빅       NaN
구구콘    2000.0
dtype: float64


중간에 nan이 들어가면 float로 바뀜

In [16]:
s2 = s2.fillna(0)
print(s2)

메로나    1000.0
비비빅       0.0
구구콘    2000.0
dtype: float64


In [17]:
price = [42500, 42550, 41800, 42550, 42650]
date = ['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27']
s = Series(price,date)
print(s)
# 시계열 데이터

2019-05-31    42500
2019-05-30    42550
2019-05-29    41800
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [18]:
data = {
    '2019-05-31' : 42500,
    '2019-05-30' : 42550,
    '2019-05-29' : 41800,
    '2019-05-28' : 42550,
    '2019-05-27' : 42650
}
s = Series(data)
print(s)

2019-05-31    42500
2019-05-30    42550
2019-05-29    41800
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [19]:
print(s.index)

Index(['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27'], dtype='str')


In [20]:
print(s.index.dtype)

str


In [21]:
print(s.values)
print(s.values.tolist())

[42500 42550 41800 42550 42650]
[42500, 42550, 41800, 42550, 42650]


# 인덱싱

In [22]:
s1 = Series([10, 20, 30])
s2 = Series([10, 20, 30], index = [1, 2, 3])
print(s1[0])
print(s2[1])

10
10


In [23]:
s3 = Series([10, 20, 30], index = ['a', 'b', 'c'])
print(s3['a'])
#print(s3[1])

10


In [24]:
s3

a    10
b    20
c    30
dtype: int64

In [25]:
print(s3.index[0])
print(s3.index[-1])

a
c


In [26]:
s = pd.Series([9904313, 123435, 5555, 6666], index=['서울','부산','인천','대구'])
s

서울    9904313
부산     123435
인천       5555
대구       6666
dtype: int64

In [27]:
print(s[1:3])

부산    123435
인천      5555
dtype: int64


숫자인덱스는 뒤에숫자 미포함

In [28]:
print(s['부산':'대구'])

부산    123435
인천      5555
대구      6666
dtype: int64


사용자지정인덱스는 뒤에문자 포함

In [29]:
print(s[1:])

부산    123435
인천      5555
대구      6666
dtype: int64


In [30]:
print(s[:2])

서울    9904313
부산     123435
dtype: int64


In [31]:
s1 = pd.Series(range(3),index=["a","b","c"])
s1

a    0
b    1
c    2
dtype: int64

In [32]:
print(s1.a)
print(s1['a'])

0
0


# 시리즈 dict

In [33]:
s = pd.Series([9904313, 123435, 5555, 6666], index=['서울','부산','인천','대구'])
s

서울    9904313
부산     123435
인천       5555
대구       6666
dtype: int64

In [34]:
print("대구" in s)

True


In [35]:
print("대전" in s)

False


In [36]:
for key, value in s.items():
    print('%s : %d' %(key,value))

서울 : 9904313
부산 : 123435
인천 : 5555
대구 : 6666


In [37]:
s2 = pd.Series({'서울':9904313, '부산':123435, '인천':5555, '대전':6666})
print(s2)

서울    9904313
부산     123435
인천       5555
대전       6666
dtype: int64


In [38]:
s2 = pd.Series({'서울':9904313, '부산':123435, '인천':5555, '대전':6666},
              index=['부산','서울','인천','대전'])
print(s2)

부산     123435
서울    9904313
인천       5555
대전       6666
dtype: int64


In [39]:
from pandas import Series
data = [1000,2000,3000]
index = ['메로나','구구콘','하겐다즈']
s = Series(data=data,index=index)
s

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64

In [40]:
print(s.iloc[0:2])      #i(integer): 위치인덱스    #i가 없으면 라벨인덱스 loc(location)

메로나    1000
구구콘    2000
dtype: int64


In [41]:
print(s.loc['메로나':'구구콘'])

메로나    1000
구구콘    2000
dtype: int64


In [42]:
indice = [0,2]
print(s.iloc[indice])

메로나     1000
하겐다즈    3000
dtype: int64


리스트로 추출

In [43]:
print(s.iloc[[0,2]])

메로나     1000
하겐다즈    3000
dtype: int64


In [44]:
indice = ['메로나','하겐다즈']
print(s.loc[indice])
print(s.loc[['메로나','하겐다즈']])

메로나     1000
하겐다즈    3000
dtype: int64
메로나     1000
하겐다즈    3000
dtype: int64


In [45]:
s.loc['메로나'] = 500     # s.iloc[0] = 500,      s['메로나'] = 500
print(s)

메로나      500
구구콘     2000
하겐다즈    3000
dtype: int64


In [46]:
s.loc['비비빅'] = 500
print(s)

메로나      500
구구콘     2000
하겐다즈    3000
비비빅      500
dtype: int64


In [47]:
s1 = s.drop('메로나')
print(s1)
print("====")
print(s)

구구콘     2000
하겐다즈    3000
비비빅      500
dtype: int64
====
메로나      500
구구콘     2000
하겐다즈    3000
비비빅      500
dtype: int64


In [48]:
s = pd.Series([92666613, 1226665, 56266, 626625], index=['서울','부산','인천','대구'])
s2 = pd.Series({'서울':9904313, '부산':123435, '인천':5555, '대전':6666},
              index=['부산','서울','인천','대전'])
ds = s - s2
print(ds)

대구           NaN
대전           NaN
부산     1103230.0
서울    82762300.0
인천       50711.0
dtype: float64


없는거 연산하면 nan

In [49]:
s3 = s / 1000000
print(s3)

서울    92.666613
부산     1.226665
인천     0.056266
대구     0.626625
dtype: float64


In [50]:
print(s.values - s2.values)

[92543178 -8677648    50711   619959]


In [51]:
print(ds[ds.notnull()])

부산     1103230.0
서울    82762300.0
인천       50711.0
dtype: float64


In [52]:
ds.notnull()

대구    False
대전    False
부산     True
서울     True
인천     True
dtype: bool

In [53]:
rs = (s-s2)/s2 * 100
print(rs)

대구           NaN
대전           NaN
부산    893.774051
서울    835.618785
인천    912.889289
dtype: float64


In [54]:
rs = rs[rs.notnull()]
print(rs)

부산    893.774051
서울    835.618785
인천    912.889289
dtype: float64


In [55]:
rs['부산']=1.63
rs['대구']=1.41
print(rs)

부산      1.630000
서울    835.618785
인천    912.889289
대구      1.410000
dtype: float64


In [56]:
del rs['서울']
print(rs)

부산      1.630000
인천    912.889289
대구      1.410000
dtype: float64


In [57]:
from pandas import Series
date = ['6/1', '6/2', '6/3', '6/4', '6/5']
high = Series([42800,42700,42050,42950,43000],index=date)
low = Series([42150,42150,41300,42150,42350],index=date)
print(high)
print('----------------')
print(low)

6/1    42800
6/2    42700
6/3    42050
6/4    42950
6/5    43000
dtype: int64
----------------
6/1    42150
6/2    42150
6/3    41300
6/4    42150
6/5    42350
dtype: int64


In [58]:
diff = high - low
print(diff)

6/1    650
6/2    550
6/3    750
6/4    800
6/5    650
dtype: int64


In [59]:
print(diff.max())

800


In [60]:
print(diff.idxmax())

6/4


In [61]:
data = {
    '삼성전자':'전기,전자',
    'LG전자':'전기,전자',
    '현대차':'운수장비',
    'NAVER':'서비스업',
    '카카오':'서비스업'
}
s = Series(data)
print(s)

삼성전자     전기,전자
LG전자     전기,전자
현대차       운수장비
NAVER     서비스업
카카오       서비스업
dtype: str


In [62]:
print(s.unique())

<StringArray>
['전기,전자', '운수장비', '서비스업']
Length: 3, dtype: str


In [63]:
print(s.value_counts())

전기,전자    2
서비스업     2
운수장비     1
Name: count, dtype: int64


In [64]:
import pandas as pd
import numpy as np
s = pd.Series(['선화','강호',np.nan,'소정','우영'])
print(s)

0     선화
1     강호
2    NaN
3     소정
4     우영
dtype: str


In [65]:
s.isnull()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [66]:
s.isna()

0    False
1    False
2     True
3    False
4    False
dtype: bool

null이 있는지

In [67]:
s[s.isnull()]

2    NaN
dtype: str

In [68]:
s[s.notnull()]

0    선화
1    강호
3    소정
4    우영
dtype: str

# 예제

In [69]:
def remove_comma(x):
    return int(x.replace(',',''))

In [70]:
s = Series(['1,234','5,678','9,876'])
result = list(s.map(remove_comma))
print(result)

[1234, 5678, 9876]


In [71]:
from pandas import Series

data = [42500, 42550, 41800, 42550, 42650]
index = ['2019-05-31', '2019-05-30','2019-05-29','2019-05-28','2019-05-27']
s = Series(data=data,index=index)
print(s)

2019-05-31    42500
2019-05-30    42550
2019-05-29    41800
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [72]:
cond = s > 42000
print(cond)

2019-05-31     True
2019-05-30     True
2019-05-29    False
2019-05-28     True
2019-05-27     True
dtype: bool


In [73]:
print(s[cond])

2019-05-31    42500
2019-05-30    42550
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [74]:
print(s[s>42000])

2019-05-31    42500
2019-05-30    42550
2019-05-28    42550
2019-05-27    42650
dtype: int64


# 정렬

In [75]:
from pandas import Series
data = [3.1,2.0,10.1,5.1]
index = ['000010','000020','000030','000040']
s = Series(data=data, index=index)
print(s)

000010     3.1
000020     2.0
000030    10.1
000040     5.1
dtype: float64


In [76]:
s1 = s.sort_values(ascending=False)
print(s1)

000030    10.1
000040     5.1
000010     3.1
000020     2.0
dtype: float64


In [77]:
s2 = s.rank(ascending=False)    #ascending=True가 기본값
print(s2)

000010    3.0
000020    4.0
000030    1.0
000040    2.0
dtype: float64
